### PR TITLE
Migrate to .NET 4.5 and ASP.NET MVC 5.2

### PR DESCRIPTION
**Pull request by shatl**
Migrate to .NET 4.5
Update dependencies  to latest versions (Json.Net 6, ASP.NET MVC 5, NHibernate 4);

NOTE:
1) SharpArchitecture-Build needs to be merged first;
2) Submodule BuildSystem reference needs to be re-pointed to SharpArchitecture repository.

### CODE REVIEW

**Comment by shatl** [comment]
@seif @kad0xf version updated to 3.0

**Comment by shatl** [comment]
Thanks @seif !
I'll create another pull request for domain signature / GetHashCode() optimization soon.

**Comment by kad0xf** [comment]
@seif, will you publish the NuGet packages or should I do it?

**Comment by seif** [comment]
Packages are already pushed.


Apologies in advance for any auto correction or spelling mistakes, sent
from my phone.

**Pull request merged**
