### PR TITLE
Upgrade NuGet dependencies, fixes #129

### LINKED ISSUE #129: Upgrade v3 dependencies
Some NuGet dependencies have new major version which is not allowed by current package settings.

E.g. Newtonsoft.Json is v7 S#Arch allows range of [6..7)

### PR DESCRIPTION
**Pull request by shatl**
Upgraded BuildSystem to support NUnit3;

Dependencies upgraded:
* Newtonsoft.Json 7.0.1^ - new major version
* NUnit 3.0.1^ - new major version
* NHibernate 4.0.4.4000^
* ASP.NET MVC 5.2.3^
* RavenDb.Client 3.0.30000^
* FluentNHibernate 2.0.3.0^

### CODE REVIEW

**Comment by seif** [comment]
@shatl failing tests in appveyor. Can you have a look?

**Comment by shatl** [comment]
Sure, will do tomorrow.

Regards,
  Vitaliy

**Comment by shatl** [comment]
Fixed! 
I checked-in appveyor configuration into repository so it can be dynamically changed

**Comment by shatl** [comment]
Fixed, please merge

Regards, Vitaliy

**Comment by seif** [comment]
@shatl I have disabled the nuget publishing from teamcity, will try to get it working from appveyor

**Comment by seif** [comment]
@shatl actually, I am going to enable the package publishing and switch to a single branch on appveyor (no need for develop) with release of SA4.0

**Comment by shatl** [comment]
Sounds good. Would you be able to publish v3.1 soon?

**Comment by seif** [comment]
It is already pushed. Tried to find a download for templify to update
template but can't download it anywhere :(


Apologies in advance for any auto correction or spelling mistakes, sent
from my phone.

**Comment by shatl** [comment]
Hmm, I see only 3.0.1 on nuget.org

**Comment by seif** [comment]
Hmm indeed. https://www.nuget.org/packages/sharp-architecture has 3.1.0 but
not other packages. Something must have gone wrong with the push. Will look
into it.

**Comment by seif** [comment]
@shatl had to up version to 3.1.1 and push to nuget again, all packages successfully pushed.

**Comment by shatl** [comment]
@seif Thanks and Happy New Year!

**Comment by seif** [comment]
No, thank you. Happy New year

**Pull request merged**
