### PR TITLE
Custom transaction isolation level support and TransactionManager updates, see #79

### PR DESCRIPTION
**Pull request by shatl**
## ASP.NET MVC
 * [BREAKING] Transaction is committed in OnActionExecuted, not OnResultExecuted() to make sure changes are persisted before rendering view.
 * [BREAKING] RollbackOnModelStateError renamed to RollbackOnModelValidationError (default: true).
 * Transaction isolation level can be specified in IsolationLevel (default: Read committed)
 * No transactions will be created for child actions.

## WebAPI
 * Transaction isolation level can be specified in IsolationLevel (default: Read committed).
 * Added RollbackOnModelValidationError (default: true).

## TransactionManager (NHibernate and RavenDB)
 * Transaction isolation level can be specified when starting transaction.

## Other hanges
* Added TransactionIsolationLevel.
* Added XML documentation.
* Updated Samples.

### CODE REVIEW

**Comment by shatl** [comment]
@seif can you please take a look

**Comment by seif** [comment]
Thanks @shatl. Time for another hangout

**Comment by shatl** [comment]
Yep, how about next Saturday?

Regards, Vitaliy

**Comment by seif** [comment]
Sounds good. I'll email you

**Pull request merged**
